on:
  push:
    branches: [ "main" ]
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Set Env.CI to false
      run: echo "CI=false" >> $GITHUB_ENV

    - name: Build
      run: |
        npm install
        npm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: host284.checkdomain.de
        username: wffyvvwy
        password: ${{ secrets.ftp_password }}
        protocol: ftp
        port: 21
        local-dir: ./build/
        server-dir: soulback.net/
